name: vicet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - torchmetrics
  - omegaconf
  - pandas
  - scikit-learn
  - pydicom
  - termcolor
  - ftfy
  - iopath
  - regex
  - submitit
  - scikit-learn-intelex
  - pip
